import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link rel="icon" href="/portfolio.jpg" type="image/png" />
      <body className={inter.className} style={{ fontFamily: 'Maven Pro, sans-serif' }}>
      <Navbar />
      {children}
     
      </body>
    </html>
  );
}
